{"level":"info","ts":"2025-09-16T18:23:15.701+0500","caller":"logger/adapter.go:53","msg":"application starting","service":"order-service-dev","env":"dev","env":"dev"}
{"level":"info","ts":"2025-09-16T18:23:15.703+0500","caller":"logger/adapter.go:53","msg":"starting metrics server","service":"order-service-dev","env":"dev","port":"9090"}
{"level":"info","ts":"2025-09-16T18:23:15.712+0500","caller":"logger/adapter.go:100","msg":"starting cache restoration from database","service":"order-service-dev","env":"dev","component":"order service"}
{"level":"error","ts":"2025-09-16T18:23:16.030+0500","caller":"logger/adapter.go:61","msg":"failed to restore cache from database","service":"order-service-dev","env":"dev","error":"service.RestoreCache: get all order uids: repository.order.GetAllOrderUIDs: query: failed to connect to `user=dev_user database=orders_db_dev`: [::1]:5432 (localhost): failed SASL auth: \ufffd\ufffd\ufffd\ufffd\ufffd: \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \"dev_user\" \ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd (\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd) (SQLSTATE 28P01)","stacktrace":"wbtest/pkg/logger.(*Adapter).Errorw\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/logger/adapter.go:61\nwbtest/internal/app.Run\n\tC:/Users/esandalov/Desktop/221/wb/l1/internal/app/app.go:62\nmain.main\n\tC:/Users/esandalov/Desktop/221/wb/l1/cmd/order-service/main.go:33\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:285"}
{"level":"info","ts":"2025-09-16T18:23:16.036+0500","caller":"logger/adapter.go:53","msg":"starting HTTP server","service":"order-service-dev","env":"dev","component":"http server","addr":"0.0.0.0:8080"}
{"level":"info","ts":"2025-09-16T18:23:16.036+0500","caller":"logger/adapter.go:100","msg":"kafka reader info","service":"order-service-dev","env":"dev","component":"kafka reader","message":"entering loop for consumer group, order-group-dev\n"}
{"level":"error","ts":"2025-09-16T18:23:16.038+0500","caller":"logger/adapter.go:61","msg":"application failed","service":"order-service-dev","env":"dev","error":"app.initKafkaComponents: kafka reader creation: kafka.checkKafkaConnection: connect to localhost:9092: failed to dial: failed to open connection to localhost:9092: dial tcp [::1]:9092: connectex: No connection could be made because the target machine actively refused it.","stacktrace":"wbtest/pkg/logger.(*Adapter).Errorw\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/logger/adapter.go:61\nmain.main\n\tC:/Users/esandalov/Desktop/221/wb/l1/cmd/order-service/main.go:35\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:285"}
{"level":"error","ts":"2025-09-16T18:23:16.038+0500","caller":"logger/adapter.go:100","msg":"kafka reader error","service":"order-service-dev","env":"dev","component":"kafka reader","error":"Unable to establish connection to consumer group coordinator for group order-group-dev: failed to dial: failed to open connection to localhost:9092: dial tcp [::1]:9092: connectex: No connection could be made because the target machine actively refused it.","stacktrace":"wbtest/pkg/logger.(*Adapter).LogAttrs\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/logger/adapter.go:100\nwbtest/pkg/kafka.NewKafkaReader.func2\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/kafka/kafka.go:36\ngithub.com/segmentio/kafka-go.LoggerFunc.Printf\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/logger.go:17\ngithub.com/segmentio/kafka-go.(*ConsumerGroup).nextGeneration.func1\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:786\ngithub.com/segmentio/kafka-go.(*ConsumerGroup).withErrorLogger\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:1248\ngithub.com/segmentio/kafka-go.(*ConsumerGroup).nextGeneration\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:785\ngithub.com/segmentio/kafka-go.(*ConsumerGroup).run\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:723\ngithub.com/segmentio/kafka-go.NewConsumerGroup.func1\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:661"}
{"level":"info","ts":"2025-09-16T18:23:16.038+0500","caller":"logger/adapter.go:53","msg":"application exited normally","service":"order-service-dev","env":"dev"}
{"level":"info","ts":"2025-09-16T18:29:02.668+0500","caller":"logger/adapter.go:53","msg":"application starting","service":"order-service-dev","env":"dev","env":"dev"}
{"level":"info","ts":"2025-09-16T18:29:02.670+0500","caller":"logger/adapter.go:53","msg":"starting metrics server","service":"order-service-dev","env":"dev","port":"9090"}
{"level":"info","ts":"2025-09-16T18:29:02.679+0500","caller":"logger/adapter.go:100","msg":"starting cache restoration from database","service":"order-service-dev","env":"dev","component":"order service"}
{"level":"error","ts":"2025-09-16T18:29:02.880+0500","caller":"logger/adapter.go:61","msg":"failed to restore cache from database","service":"order-service-dev","env":"dev","error":"service.RestoreCache: get all order uids: repository.order.GetAllOrderUIDs: query: failed to connect to `user=dev_user database=orders_db_dev`: [::1]:5432 (localhost): failed SASL auth: \ufffd\ufffd\ufffd\ufffd\ufffd: \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \"dev_user\" \ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd (\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd) (SQLSTATE 28P01)","stacktrace":"wbtest/pkg/logger.(*Adapter).Errorw\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/logger/adapter.go:61\nwbtest/internal/app.Run\n\tC:/Users/esandalov/Desktop/221/wb/l1/internal/app/app.go:62\nmain.main\n\tC:/Users/esandalov/Desktop/221/wb/l1/cmd/order-service/main.go:33\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:285"}
{"level":"info","ts":"2025-09-16T18:29:02.884+0500","caller":"logger/adapter.go:53","msg":"starting HTTP server","service":"order-service-dev","env":"dev","component":"http server","addr":"0.0.0.0:8080"}
{"level":"info","ts":"2025-09-16T18:29:02.885+0500","caller":"logger/adapter.go:100","msg":"kafka reader info","service":"order-service-dev","env":"dev","component":"kafka reader","message":"entering loop for consumer group, order-group-dev\n"}
{"level":"error","ts":"2025-09-16T18:29:02.889+0500","caller":"logger/adapter.go:61","msg":"application failed","service":"order-service-dev","env":"dev","error":"app.initKafkaComponents: kafka reader creation: kafka.checkKafkaConnection: connect to localhost:9092: failed to dial: failed to open connection to localhost:9092: dial tcp [::1]:9092: connectex: No connection could be made because the target machine actively refused it.","stacktrace":"wbtest/pkg/logger.(*Adapter).Errorw\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/logger/adapter.go:61\nmain.main\n\tC:/Users/esandalov/Desktop/221/wb/l1/cmd/order-service/main.go:35\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:285"}
{"level":"error","ts":"2025-09-16T18:29:02.889+0500","caller":"logger/adapter.go:100","msg":"kafka reader error","service":"order-service-dev","env":"dev","component":"kafka reader","error":"Unable to establish connection to consumer group coordinator for group order-group-dev: failed to dial: failed to open connection to localhost:9092: dial tcp [::1]:9092: connectex: No connection could be made because the target machine actively refused it.","stacktrace":"wbtest/pkg/logger.(*Adapter).LogAttrs\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/logger/adapter.go:100\nwbtest/pkg/kafka.NewKafkaReader.func2\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/kafka/kafka.go:36\ngithub.com/segmentio/kafka-go.LoggerFunc.Printf\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/logger.go:17\ngithub.com/segmentio/kafka-go.(*ConsumerGroup).nextGeneration.func1\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:786\ngithub.com/segmentio/kafka-go.(*ConsumerGroup).withErrorLogger\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:1248\ngithub.com/segmentio/kafka-go.(*ConsumerGroup).nextGeneration\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:785\ngithub.com/segmentio/kafka-go.(*ConsumerGroup).run\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:723\ngithub.com/segmentio/kafka-go.NewConsumerGroup.func1\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:661"}
{"level":"info","ts":"2025-09-16T18:29:02.889+0500","caller":"logger/adapter.go:53","msg":"application exited normally","service":"order-service-dev","env":"dev"}
{"level":"info","ts":"2025-09-16T18:35:23.710+0500","caller":"logger/adapter.go:53","msg":"application starting","service":"order-service-dev","env":"dev","env":"dev"}
{"level":"info","ts":"2025-09-16T18:35:23.713+0500","caller":"logger/adapter.go:53","msg":"starting metrics server","service":"order-service-dev","env":"dev","port":"9090"}
{"level":"info","ts":"2025-09-16T18:35:23.721+0500","caller":"logger/adapter.go:100","msg":"starting cache restoration from database","service":"order-service-dev","env":"dev","component":"order service"}
{"level":"error","ts":"2025-09-16T18:35:23.967+0500","caller":"logger/adapter.go:61","msg":"failed to restore cache from database","service":"order-service-dev","env":"dev","error":"service.RestoreCache: get all order uids: repository.order.GetAllOrderUIDs: query: failed to connect to `user=dev_user database=orders_db_dev`: [::1]:5432 (localhost): failed SASL auth: \ufffd\ufffd\ufffd\ufffd\ufffd: \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \"dev_user\" \ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd (\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd) (SQLSTATE 28P01)","stacktrace":"wbtest/pkg/logger.(*Adapter).Errorw\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/logger/adapter.go:61\nwbtest/internal/app.Run\n\tC:/Users/esandalov/Desktop/221/wb/l1/internal/app/app.go:62\nmain.main\n\tC:/Users/esandalov/Desktop/221/wb/l1/cmd/order-service/main.go:33\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:285"}
{"level":"info","ts":"2025-09-16T18:35:23.981+0500","caller":"logger/adapter.go:53","msg":"starting HTTP server","service":"order-service-dev","env":"dev","component":"http server","addr":"0.0.0.0:8080"}
{"level":"info","ts":"2025-09-16T18:35:23.982+0500","caller":"logger/adapter.go:100","msg":"kafka reader info","service":"order-service-dev","env":"dev","component":"kafka reader","message":"entering loop for consumer group, order-group-dev\n"}
{"level":"error","ts":"2025-09-16T18:35:23.986+0500","caller":"logger/adapter.go:61","msg":"application failed","service":"order-service-dev","env":"dev","error":"app.initKafkaComponents: kafka reader creation: kafka.checkKafkaConnection: connect to localhost:9092: failed to dial: failed to open connection to localhost:9092: dial tcp [::1]:9092: connectex: No connection could be made because the target machine actively refused it.","stacktrace":"wbtest/pkg/logger.(*Adapter).Errorw\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/logger/adapter.go:61\nmain.main\n\tC:/Users/esandalov/Desktop/221/wb/l1/cmd/order-service/main.go:35\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:285"}
{"level":"error","ts":"2025-09-16T18:35:23.987+0500","caller":"logger/adapter.go:100","msg":"kafka reader error","service":"order-service-dev","env":"dev","component":"kafka reader","error":"Unable to establish connection to consumer group coordinator for group order-group-dev: failed to dial: failed to open connection to localhost:9092: dial tcp [::1]:9092: connectex: No connection could be made because the target machine actively refused it.","stacktrace":"wbtest/pkg/logger.(*Adapter).LogAttrs\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/logger/adapter.go:100\nwbtest/pkg/kafka.NewKafkaReader.func2\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/kafka/kafka.go:36\ngithub.com/segmentio/kafka-go.LoggerFunc.Printf\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/logger.go:17\ngithub.com/segmentio/kafka-go.(*ConsumerGroup).nextGeneration.func1\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:786\ngithub.com/segmentio/kafka-go.(*ConsumerGroup).withErrorLogger\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:1248\ngithub.com/segmentio/kafka-go.(*ConsumerGroup).nextGeneration\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:785\ngithub.com/segmentio/kafka-go.(*ConsumerGroup).run\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:723\ngithub.com/segmentio/kafka-go.NewConsumerGroup.func1\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:661"}
{"level":"info","ts":"2025-09-16T18:35:23.988+0500","caller":"logger/adapter.go:53","msg":"application exited normally","service":"order-service-dev","env":"dev"}
{"level":"error","ts":"2025-09-16T18:35:23.990+0500","caller":"logger/adapter.go:100","msg":"kafka reader error","service":"order-service-dev","env":"dev","component":"kafka reader","error":"failed to dial: failed to open connection to localhost:9092: dial tcp [::1]:9092: connectex: No connection could be made because the target machine actively refused it.","stacktrace":"wbtest/pkg/logger.(*Adapter).LogAttrs\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/logger/adapter.go:100\nwbtest/pkg/kafka.NewKafkaReader.func2\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/kafka/kafka.go:36\ngithub.com/segmentio/kafka-go.LoggerFunc.Printf\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/logger.go:17\ngithub.com/segmentio/kafka-go.(*Reader).run.func2\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/reader.go:314\ngithub.com/segmentio/kafka-go.(*Reader).withErrorLogger\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/reader.go:1139\ngithub.com/segmentio/kafka-go.(*Reader).run\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/reader.go:313"}
{"level":"info","ts":"2025-09-22T10:19:30.019+0500","caller":"logger/adapter.go:53","msg":"application starting","service":"order-service-dev","env":"dev","env":"dev"}
{"level":"info","ts":"2025-09-22T10:19:30.021+0500","caller":"logger/adapter.go:53","msg":"starting metrics server","service":"order-service-dev","env":"dev","port":"9090"}
{"level":"info","ts":"2025-09-22T10:19:30.029+0500","caller":"logger/adapter.go:100","msg":"starting cache restoration from database","service":"order-service-dev","env":"dev","component":"order service"}
{"level":"error","ts":"2025-09-22T10:19:30.708+0500","caller":"logger/adapter.go:61","msg":"failed to restore cache from database","service":"order-service-dev","env":"dev","error":"service.RestoreCache: get all order uids: repository.order.GetAllOrderUIDs: query: failed to connect to `user=dev_user database=orders_db_dev`: [::1]:5432 (localhost): failed SASL auth: \ufffd\ufffd\ufffd\ufffd\ufffd: \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \"dev_user\" \ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd (\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd) (SQLSTATE 28P01)","stacktrace":"wbtest/pkg/logger.(*Adapter).Errorw\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/logger/adapter.go:61\nwbtest/internal/app.Run\n\tC:/Users/esandalov/Desktop/221/wb/l1/internal/app/app.go:62\nmain.main\n\tC:/Users/esandalov/Desktop/221/wb/l1/cmd/order-service/main.go:33\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:285"}
{"level":"info","ts":"2025-09-22T10:20:27.151+0500","caller":"logger/adapter.go:53","msg":"application starting","service":"order-service-dev","env":"dev","env":"dev"}
{"level":"info","ts":"2025-09-22T10:20:27.153+0500","caller":"logger/adapter.go:53","msg":"starting metrics server","service":"order-service-dev","env":"dev","port":"9090"}
{"level":"info","ts":"2025-09-22T10:20:27.161+0500","caller":"logger/adapter.go:100","msg":"starting cache restoration from database","service":"order-service-dev","env":"dev","component":"order service"}
{"level":"error","ts":"2025-09-22T10:20:27.287+0500","caller":"logger/adapter.go:61","msg":"failed to restore cache from database","service":"order-service-dev","env":"dev","error":"service.RestoreCache: get all order uids: repository.order.GetAllOrderUIDs: query: failed to connect to `user=dev_user database=orders_db_dev`: [::1]:5432 (localhost): failed SASL auth: \ufffd\ufffd\ufffd\ufffd\ufffd: \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \"dev_user\" \ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd (\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd) (SQLSTATE 28P01)","stacktrace":"wbtest/pkg/logger.(*Adapter).Errorw\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/logger/adapter.go:61\nwbtest/internal/app.Run\n\tC:/Users/esandalov/Desktop/221/wb/l1/internal/app/app.go:62\nmain.main\n\tC:/Users/esandalov/Desktop/221/wb/l1/cmd/order-service/main.go:33\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:285"}
{"level":"info","ts":"2025-09-22T10:20:27.299+0500","caller":"logger/adapter.go:53","msg":"starting HTTP server","service":"order-service-dev","env":"dev","component":"http server","addr":"0.0.0.0:8080"}
{"level":"error","ts":"2025-09-22T10:20:27.304+0500","caller":"logger/adapter.go:61","msg":"application failed","service":"order-service-dev","env":"dev","error":"app.initKafkaComponents: kafka reader creation: kafka.checkKafkaConnection: connect to localhost:9092: failed to dial: failed to open connection to localhost:9092: dial tcp [::1]:9092: connectex: No connection could be made because the target machine actively refused it.","stacktrace":"wbtest/pkg/logger.(*Adapter).Errorw\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/logger/adapter.go:61\nmain.main\n\tC:/Users/esandalov/Desktop/221/wb/l1/cmd/order-service/main.go:35\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:285"}
{"level":"error","ts":"2025-09-22T10:20:27.304+0500","caller":"logger/adapter.go:100","msg":"kafka reader error","service":"order-service-dev","env":"dev","component":"kafka reader","error":"Unable to establish connection to consumer group coordinator for group order-group-dev: failed to dial: failed to open connection to localhost:9092: dial tcp [::1]:9092: connectex: No connection could be made because the target machine actively refused it.","stacktrace":"wbtest/pkg/logger.(*Adapter).LogAttrs\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/logger/adapter.go:100\nwbtest/pkg/kafka.NewKafkaReader.func2\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/kafka/kafka.go:36\ngithub.com/segmentio/kafka-go.LoggerFunc.Printf\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/logger.go:17\ngithub.com/segmentio/kafka-go.(*ConsumerGroup).nextGeneration.func1\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:786\ngithub.com/segmentio/kafka-go.(*ConsumerGroup).withErrorLogger\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:1248\ngithub.com/segmentio/kafka-go.(*ConsumerGroup).nextGeneration\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:785\ngithub.com/segmentio/kafka-go.(*ConsumerGroup).run\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:723\ngithub.com/segmentio/kafka-go.NewConsumerGroup.func1\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:661"}
{"level":"info","ts":"2025-09-22T10:20:27.308+0500","caller":"logger/adapter.go:100","msg":"kafka reader info","service":"order-service-dev","env":"dev","component":"kafka reader","message":"entering loop for consumer group, order-group-dev\n"}
{"level":"info","ts":"2025-09-22T10:20:27.308+0500","caller":"logger/adapter.go:53","msg":"application exited normally","service":"order-service-dev","env":"dev"}
{"level":"error","ts":"2025-09-22T10:20:27.311+0500","caller":"logger/adapter.go:100","msg":"kafka reader error","service":"order-service-dev","env":"dev","component":"kafka reader","error":"failed to dial: failed to open connection to localhost:9092: dial tcp [::1]:9092: connectex: No connection could be made because the target machine actively refused it.","stacktrace":"wbtest/pkg/logger.(*Adapter).LogAttrs\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/logger/adapter.go:100\nwbtest/pkg/kafka.NewKafkaReader.func2\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/kafka/kafka.go:36\ngithub.com/segmentio/kafka-go.LoggerFunc.Printf\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/logger.go:17\ngithub.com/segmentio/kafka-go.(*Reader).run.func2\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/reader.go:314\ngithub.com/segmentio/kafka-go.(*Reader).withErrorLogger\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/reader.go:1139\ngithub.com/segmentio/kafka-go.(*Reader).run\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/reader.go:313"}
{"level":"info","ts":"2025-09-22T10:21:47.781+0500","caller":"logger/adapter.go:53","msg":"application starting","service":"order-service-dev","env":"dev","env":"dev"}
{"level":"info","ts":"2025-09-22T10:21:47.782+0500","caller":"logger/adapter.go:53","msg":"starting metrics server","service":"order-service-dev","env":"dev","port":"9090"}
{"level":"info","ts":"2025-09-22T10:21:47.793+0500","caller":"logger/adapter.go:100","msg":"starting cache restoration from database","service":"order-service-dev","env":"dev","component":"order service"}
{"level":"error","ts":"2025-09-22T10:21:47.979+0500","caller":"logger/adapter.go:61","msg":"failed to restore cache from database","service":"order-service-dev","env":"dev","error":"service.RestoreCache: get all order uids: repository.order.GetAllOrderUIDs: query: failed to connect to `user=dev_user database=orders_db_dev`: [::1]:5432 (localhost): failed SASL auth: \ufffd\ufffd\ufffd\ufffd\ufffd: \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \"dev_user\" \ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd (\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd) (SQLSTATE 28P01)","stacktrace":"wbtest/pkg/logger.(*Adapter).Errorw\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/logger/adapter.go:61\nwbtest/internal/app.Run\n\tC:/Users/esandalov/Desktop/221/wb/l1/internal/app/app.go:62\nmain.main\n\tC:/Users/esandalov/Desktop/221/wb/l1/cmd/order-service/main.go:33\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:285"}
{"level":"info","ts":"2025-09-22T10:21:47.986+0500","caller":"logger/adapter.go:53","msg":"starting HTTP server","service":"order-service-dev","env":"dev","component":"http server","addr":"0.0.0.0:8080"}
{"level":"info","ts":"2025-09-22T10:21:47.987+0500","caller":"logger/adapter.go:100","msg":"kafka reader info","service":"order-service-dev","env":"dev","component":"kafka reader","message":"entering loop for consumer group, order-group-dev\n"}
{"level":"error","ts":"2025-09-22T10:21:47.989+0500","caller":"logger/adapter.go:61","msg":"application failed","service":"order-service-dev","env":"dev","error":"app.initKafkaComponents: kafka reader creation: kafka.checkKafkaConnection: connect to localhost:9092: failed to dial: failed to open connection to localhost:9092: dial tcp [::1]:9092: connectex: No connection could be made because the target machine actively refused it.","stacktrace":"wbtest/pkg/logger.(*Adapter).Errorw\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/logger/adapter.go:61\nmain.main\n\tC:/Users/esandalov/Desktop/221/wb/l1/cmd/order-service/main.go:35\nruntime.main\n\tC:/Program Files/Go/src/runtime/proc.go:285"}
{"level":"error","ts":"2025-09-22T10:21:47.989+0500","caller":"logger/adapter.go:100","msg":"kafka reader error","service":"order-service-dev","env":"dev","component":"kafka reader","error":"Unable to establish connection to consumer group coordinator for group order-group-dev: failed to dial: failed to open connection to localhost:9092: dial tcp [::1]:9092: connectex: No connection could be made because the target machine actively refused it.","stacktrace":"wbtest/pkg/logger.(*Adapter).LogAttrs\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/logger/adapter.go:100\nwbtest/pkg/kafka.NewKafkaReader.func2\n\tC:/Users/esandalov/Desktop/221/wb/l1/pkg/kafka/kafka.go:36\ngithub.com/segmentio/kafka-go.LoggerFunc.Printf\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/logger.go:17\ngithub.com/segmentio/kafka-go.(*ConsumerGroup).nextGeneration.func1\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:786\ngithub.com/segmentio/kafka-go.(*ConsumerGroup).withErrorLogger\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:1248\ngithub.com/segmentio/kafka-go.(*ConsumerGroup).nextGeneration\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:785\ngithub.com/segmentio/kafka-go.(*ConsumerGroup).run\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:723\ngithub.com/segmentio/kafka-go.NewConsumerGroup.func1\n\tC:/Users/esandalov/go/bin/pkg/mod/github.com/segmentio/kafka-go@v0.4.49/consumergroup.go:661"}
{"level":"info","ts":"2025-09-22T10:21:47.990+0500","caller":"logger/adapter.go:53","msg":"application exited normally","service":"order-service-dev","env":"dev"}
